word-counter : word-counter.c
	@echo "Compiling Word Counter Function in C code."
	@gcc word-counter.c -o word-counter
	@chmod +x word-counter

clean :
	@echo "Cleaning everything but the source files."
	@rm word-counter